language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-25.0.1
    - android-25
    - extra-android-support
    - extra-android-m2repository
    
script:
        - ./gradlew build
before_install:
        - chmod +x gradlew

branches:
  only:
  - master  
  - develop